# ベースとなる情報（定数）をまとめる
config:
  normConfigName: 'norm_config.yml'
  stdParamsName: 'std_params.json'
env: # 環境の情報
  agents: 2
model: # model作成に必要な情報
  observationClassName: Observation #norm_configで指定しているObservation用のクラス（Observationのサイズ計算用）
  actorModelName: actorModel
  vModelName: vModel
  qModelName: qModel
  stateEncoderModelName: stateEncoder
  actions: 34
  hyperParameters:
    StateEncoder:
      out_dim: 128
      ObservationEncoder:
        rho: 0.05
        beta: 3
        lr: 0.01
      ObservationActionPairEncoder:
        rho: 0.05
        beta: 3
        lr: 0.01
    Actor:
      num_heads: 3
      lr: 0.01
    VModel:
      hid_dim: 64
      num_heads: 3
      lr: 0.01
      lam: 0.5
      gam: 0.5
      lam_eps: 1e-7
      gam_eps: 1e-7
    QModel:
      hid_dim: 64
      num_heads: 3
      lr: 0.01
